name: deploy
on:
    push:
        branches:
            - main # 当 main 分支有新的 push 操作时触发部署
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 # 检出代码

            - name: Install and Build
              run: |
                  npm ci # 安装依赖
                  npm run build # 构建项目

            # 下面是部署操作
            - name: Upload dist to server
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -avzr --delete
                  path: dist/
                  remote_path: ${{ secrets.SERVER_PATH }}
                  remote_host: ${{ secrets.SERVER_IP }}
                  remote_user: ${{ secrets.SERVER_USER }}
                  remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
